@if (config('app.livemedia'))
    <!-- Charlie Adam -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:343px;"><div style="overflow:hidden;position:relative;height:0;padding:173.177843% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/123974487?et=9offnmhRQPVxh5GeiNJu6Q&viewMoreLink=off&sig=89MF3OXp8TX3dTbGS_hSEx2dSlnYognMqL9cbo8yNic=" width="343" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/123974487" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Graham Alexander -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:386px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/73697613" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:153.886010% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/73697613?et=uGReHFq1RztFMHTcwNzAkg&viewMoreLink=off&sig=0jzhqSyLNMDvo_hIO2VhrrQgMkL1mPxuEXk9qonejAI=&caption=true" width="386" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Steve Archibald -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:567px;"><div style="overflow:hidden;position:relative;height:0;padding:104.761905% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/93713688?et=zCJaLUk7TRVqliGrQTpJMw&viewMoreLink=off&sig=oak1xSoGevuQNuo0Lr27YSdtTQB5tJopMBL2tthO8LY=" width="567" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/93713688" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Barry Bannan -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/454896684" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/454896684?et=bRfQl4JDSOVoYwtCMgs8RA&viewMoreLink=off&sig=cGs7DZmInQS42AaX5ZnkjvHalS09Dv0-bWRWJZHRi24=&caption=true" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Christophe Berra -->
	<div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:432px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/594785086" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:137.500000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/594785086?et=Cvtw4MQVR1Z8OR9W8fdzAQ&viewMoreLink=off&sig=afRlkRuLkBkpJjAfrm76idb_yNAkAfqmEWC0E9Mf7dA=&caption=true" width="432" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Scott Booth -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:394px;"><div style="overflow:hidden;position:relative;height:0;padding:150.761421% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1631458?et=GYleGgsiSy1a8vWMGObAow&viewMoreLink=off&sig=oXjGKfIG8SDNJEH3nRcwMxSRyHocvqNKYdk4GmTm4fU=" width="394" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1631458" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Tom Boyd -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:432px;"><div style="overflow:hidden;position:relative;height:0;padding:137.500000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/52938791?et=bved1tYFTJNOm9qBomJPMw&viewMoreLink=off&sig=izi02L3GA4N6SLeuV45jBW9k48tkU4P1XjupAOA9LDY=" width="432" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/52938791" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Craig Burley -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:332px;"><div style="overflow:hidden;position:relative;height:0;padding:178.915663% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79036973?et=yUtwEpW2RvZSkLyQHHc4Pw&viewMoreLink=off&sig=vFF41Ovr1EPbJd_yt0P6hEdn4TXHgFe-KtbSk_DX1WU=" width="332" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79036973" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Colin Calderwood -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:371px;"><div style="overflow:hidden;position:relative;height:0;padding:160.107817% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79036964?et=9X0aSHk0S851iYcA4308iA&viewMoreLink=off&sig=ZtZ1MmqwotoM6KQXFhHUIJFU2RpEA6fj_Nlx89uI2no=" width="371" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79036964" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- John Collins -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:394px;"><div style="overflow:hidden;position:relative;height:0;padding:150.761421% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1632051?et=kXNArBzAQy9ja21PTdWhQw&viewMoreLink=off&sig=P_TVyyoahDS_mhGjF-wVpbutXPZYkb_M0JBuf9YKUmY=" width="394" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1632051" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Stevie Crawford -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:436px;"><div style="overflow:hidden;position:relative;height:0;padding:136.238532% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/2589887?et=KxTKl5iWTjlA8EFtwxC1Ig&viewMoreLink=off&sig=PoDXZ7FyRd27OhtLiX9t185nxxYJfMD2t4Rgm_ctxgU=" width="436" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/2589887" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Kenny Dalglish -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:256px;"><div style="overflow:hidden;position:relative;height:0;padding:232.031250% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/93713666?et=fO7s4LW_T5lKT2mO608pdw&viewMoreLink=off&sig=1FeiHZr1UA_JJmkj3mmpBtK92vZij74-k9jOL4kOVpM=" width="256" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/93713666" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Billy Dodds -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:408px;"><div style="overflow:hidden;position:relative;height:0;padding:145.588235% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1204888?et=1wSiJbfDR0NBgoRq5sxXww&viewMoreLink=off&sig=B7xMiR6PhGdGg1Y8LoIfmvWdA8K5A6OxnirT4bjap28=" width="408" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1204888" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Gordon Durie -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:390px;"><div style="overflow:hidden;position:relative;height:0;padding:152.307692% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1269975?et=JDkM-XLtS-5432RK_ekEgA&viewMoreLink=off&sig=F0-YooDyoq8y1VWKTs31cgmG1pmf1PrhWNpcu7z15CQ=" width="390" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1269975" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Barry Ferguson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:415px;"><div style="overflow:hidden;position:relative;height:0;padding:143.132530% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/83758471?et=Ig5lJVLqSihQRkp0O8-jKg&viewMoreLink=off&sig=idikrAgLTgm9GhIiHkTJVMsau1Z4m7h4dWXVfo4J2-M=" width="415" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/83758471" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Steven Fletcher -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/468026722" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/468026722?et=pGIEnQmARDpjmvvQgaNXFw&viewMoreLink=off&sig=46OTxLlehjIN2JrN6mLApquEe9rpoNcNEWVJ77iyVbo=&caption=true" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Kevin Gallacher -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1237354?et=tZY4wk1FSgZ5VqdRImarGg&viewMoreLink=off&sig=H2w7H-kSnbREjvuRCwjzKb8QTjgh5U_O1-GuALV9Mw0=" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1237354" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Andy Goram -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1632227?et=dC_c1y6TQ-xh7zKBd8yUyQ&viewMoreLink=off&sig=hb4Zd__UEzbFajSTT-wTEe8OwVPlX0J51gFkS9AOf4Y=" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1632227" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Richard Gough -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:426px;"><div style="overflow:hidden;position:relative;height:0;padding:139.436620% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/461528116?et=Y4e1v6MxSk5eqWZdoaMbNQ&viewMoreLink=off&sig=zAc0nwPkPVM96koPVbOgm168ybx1F0mc9UCvIVtaLqs=" width="426" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/461528116" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Frank Gray -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/78991342" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78991342?et=uCdTBv2-RIhYn5HscL6DAQ&viewMoreLink=off&sig=yX8dSa8MXCFjnLWDg8T7wV74eftWtazI32SaeFDl7BQ=&caption=true" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Alan Hansen -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:358px;"><div style="overflow:hidden;position:relative;height:0;padding:165.921788% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79046585?et=YkMeLv-jRSJw5ICWIsg_Fw&viewMoreLink=off&sig=NJOvfwU9sewSaApmemp58XmKim4md8ZRTVY7LU9cp3A=" width="358" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79046585" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Paul Hartley -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:438px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/55880488" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:135.616438% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/55880488?et=1x-vfUPlQ6JPiaifbxmI4w&viewMoreLink=off&sig=32DBq9C20qz3Ds0PZcpIMHiWL1DaAmwi5Vn4tclCjKE=&caption=true" width="438" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Don Hutchison -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:382px;"><div style="overflow:hidden;position:relative;height:0;padding:155.497382% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/955887?et=lTA5vmtISUlYsFZEbK3dGQ&viewMoreLink=off&sig=tUWcP13Di4fGiwok_mNaSLBn5nLzHMPvFkNdXpxtqc4=" width="382" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/955887" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Darren Jackson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:393px;"><div style="overflow:hidden;position:relative;height:0;padding:151.145038% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1529638?et=b5zhg-pVRwJOxB3hsIaYIg&viewMoreLink=off&sig=j28L2v9wlEfyYnVxrm4J3K-EIEpvvublh4QDxlzg-3o=" width="393" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1529638" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Allan Johnston -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:407px;"><div style="overflow:hidden;position:relative;height:0;padding:145.945946% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1185059?et=uIOuayAUQalLL0k9xXJ1uQ&viewMoreLink=off&sig=-HCEaX0wwDVUl_RSGEL76zMGc3-j3QIaRWbQB0vvTHU=" width="407" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1185059" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Joe Jordan -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:422px;"><div style="overflow:hidden;position:relative;height:0;padding:140.758294% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78982535?et=msLoBVFzRCpz6UI2PHnBpw&viewMoreLink=off&sig=TC50PjOQNvPJ7Ith68cfCNQr5EBYwnkfcUNmGuqjJyQ=" width="422" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78982535" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Jim Leighton -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:402px;"><div style="overflow:hidden;position:relative;height:0;padding:147.761194% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/174044947?et=BEvdpiraTcZ46YAeQk74Fw&viewMoreLink=off&sig=-ZHsiFMIO08RBPdh4XIew4-hTzFuojeZ87FzDewKYEY=" width="402" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/174044947" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Peter Lorimer -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:594px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/541941058" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:85.185185% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/541941058?et=olsig96tQQ5AfJocW3DuBQ&viewMoreLink=off&sig=8_WcfIAHMCEQfDclrbGZ7VzdcW2PZcaw5aIK5qUdqJE=&caption=true" width="594" height="506" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Murdo MacLeod -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:411px;"><div style="overflow:hidden;position:relative;height:0;padding:144.525547% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79034917?et=5feFgJ4kQzZ-IQq6t6TeoA&viewMoreLink=off&sig=NzeutBF_TyCRSVLUMl45vkQxtmCuDDgl6fbyFrGwWA4=" width="411" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79034917" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Maurice Malpas -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:388px;"><div style="overflow:hidden;position:relative;height:0;padding:153.092784% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79029134?et=6Jf8R-ReTGhZ8fy0wWQPhQ&viewMoreLink=off&sig=IcTWlukitxbJQsQ4E4LT2dYHXmO31GTHRW1Bpl846ZU=" width="388" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79029134" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Russell Martin -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:441px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/179810197" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:134.693878% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/179810197?et=Eha42FHJTg5qYWkAEIcq6g&viewMoreLink=off&sig=0rgvQ8zeml8YH9c44aoEHo6dnRP_Q-rYvYB2dVptKuU=&caption=true" width="441" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Gary McAllister -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:394px;"><div style="overflow:hidden;position:relative;height:0;padding:150.761421% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1920622?et=16EF0F2TTEJFffbs3Xa0rw&viewMoreLink=off&sig=DVVBteeiDPOrxj-kw5ZiZ8Jb2eeVpfCddIMNGJIxjEE=" width="394" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1920622" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Brian McClair -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:374px;"><div style="overflow:hidden;position:relative;height:0;padding:158.823529% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79648395?et=OFaqgju0ToZa7Bo3asb_eA&viewMoreLink=off&sig=m1t5k2y517TkM6fdG4I1izeKgvsvdfpfC0dfLFNcjh0=" width="374" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79648395" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- James McFadden -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:410px;"><div style="overflow:hidden;position:relative;height:0;padding:144.878049% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/71773873?et=AY2Lk-4-RQhLGa-EAtnbXg&viewMoreLink=off&sig=IUFu0p65sFAqVC4zd8mgGYiOYlUQPjS_5a8FT1C-wDc=" width="410" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/71773873" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Danny McGrain -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:382px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/79648568" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:155.497382% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79648568?et=-pXbQcaNSyVB6smKsouRog&viewMoreLink=off&sig=0xMwyoRQ35QaWjTSuAGxLKWyAkH3iAmeGI-zHGgkpcU=&caption=true" width="382" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Billy McKinlay -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1639602?et=91CwOYkwR4tdeQ0W-tyKnA&viewMoreLink=off&sig=EIHhdsxdNvx_4bDN6amjDg2lByN3VmhD6WB531kpnBw=" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1639602" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Tosh McKinlay -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:344px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/79036874" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:172.674419% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79036874?et=AN9VhYoLTmZrZfqOkH4JGQ&viewMoreLink=off&sig=r3Ijy4LykNd5dTVuqzTqE5rVE5vizalXg8IguYvmJ_o=&caption=true" width="344" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Jackie McNamara -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:366px;"><div style="overflow:hidden;position:relative;height:0;padding:162.295082% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/2522465?et=pWQsOLEJSzNJ54N1f9kmHQ&viewMoreLink=off&sig=W3mmy5ct1kMT63n0Fz_J5piggMoSiU698A8Fs6aFBsA=" width="366" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/2522465" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Kenny Miller -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/110933285?et=nfcEq61vSpdbPYILnAVRhg&viewMoreLink=off&sig=I6rXjCuJMtKsy-3kXBmMYZY9grJunmQRsrRrkjAjlB8=" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/110933285" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- James Morrison -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/487262784?et=bKkNDeyJQl1yzhAy2kwUiw&viewMoreLink=off&sig=3uujVIjenl9wzOt4iEVOjn4ItPOPLqwdMduoXdK1DRE=" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/487262784" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- David Narey -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:390px;"><div style="overflow:hidden;position:relative;height:0;padding:152.307692% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79045197?et=D23Z8glkTz1sJBwyDctn0A&viewMoreLink=off&sig=-7i14ppVjXdf2ugbylOkV73gPn9TJGr_CcQzeH7sI3o=" width="390" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79045197" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Charlie Nicholas -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:385px;"><div style="overflow:hidden;position:relative;height:0;padding:154.285714% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1640839?et=i-9Up3L9TZVyV2dzvsVf6g&viewMoreLink=off&sig=4h5Ny8wEqeC2y6O4wd4WiKcCkuopXsD_ipGGzwBKPOA=" width="385" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1640839" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Steve Nicol -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:390px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/79647981" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:152.307692% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79647981?et=Eftox0xRSYxzFT-fD9G1qQ&viewMoreLink=off&sig=lrGFJjVJ4ZGL1lAkHnzKvZDnG_vLuR6B2ChfHGrphS8=&caption=true" width="390" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Davie Provan -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:409px;"><div style="overflow:hidden;position:relative;height:0;padding:145.232274% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/467509150?et=gh94VDX_Q2tjJPvJGrNuvg&viewMoreLink=off&sig=SRZPf6zVBbwrIyHA-OrdEKKDuK6vLIMCj6CRqErOTy8=" width="409" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/467509150" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Bruce Rioch -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:456px;"><div style="overflow:hidden;position:relative;height:0;padding:130.263158% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1232148?et=VFXoMXgDSWJ5Fv79Wdvbug&viewMoreLink=off&sig=bYZUUUmWA1HgI4cV706x7KpsWq7n1qAoSAJK1jqNXN4=" width="456" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1232148" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Matt Richie -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:397px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/492768774" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:149.622166% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/492768774?et=3J_PXS5FRoVtkveu7V66BQ&viewMoreLink=off&sig=riAKScp3niqR1RBw4mrjgUAQNrfXMrPzUQKnIBfwo4E=&caption=true" width="397" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Andrew Robertson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:Roboto,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:406px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.co.uk/detail/694752506" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:146.30542% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/694752506?et=Vzbe7AviQolKuBdMuqmOaQ&tld=co.uk&sig=pQ2ovfr6Waooc69gUF5YcUztSkbRrDS3HsUixpKj2lE=&caption=true&ver=1" scrolling="no" frameborder="0" width="406" height="594" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div></div>
    <!-- Barry Robson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:376px;"><div style="overflow:hidden;position:relative;height:0;padding:157.978723% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/83243743?et=3k2mZaS5R0x5ZlI5tb86zg&viewMoreLink=off&sig=gYmARL5EhvRj2zrQS9OCF_WWsfN_ybwjqUBzWOSKkoY=" width="376" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/83243743" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Graeme Sharp -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:407px;"><div style="overflow:hidden;position:relative;height:0;padding:145.945946% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78968917?et=Rz9xIfieQc1Kl7X-vdlliQ&viewMoreLink=off&sig=CMIzSZZJjXPDykV3OD1wmsuR3OwGif46XJnoFv09XcE=" width="407" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78968917" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Graeme Souness -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:312px;"><div style="overflow:hidden;position:relative;height:0;padding:142.788462% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79652764?et=OKjnCxqaR4tZW69ZUuQC9A&viewMoreLink=off&sig=iwbObUgeHCNLyrGGGbvGHTvAZnm1mRVVfX1W6f6o9LQ=" width="312" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79652764" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- David Speedie -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:403px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/89114113" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:147.394541% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/89114113?et=CWcNdXNfRtdsWqOcslW8_A&viewMoreLink=off&sig=fHGTzSXZoa7GyKMjONlOZBHFLcixCZFEJjglBPrJRP0=&caption=true" width="403" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Gordon Strachan -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:344px;"><div style="overflow:hidden;position:relative;height:0;padding:129.411765% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/467597720?et=EUwo1mlaT-REQF9-q_F7Iw&viewMoreLink=off&sig=3b3YwVQfUYgkihBdDdJTPCuoUniawZJj368NoKIadL8=" width="344" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/467597720" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Neil Sullivan -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:309px;"><div style="overflow:hidden;position:relative;height:0;padding:144.174757% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79021318?et=XJVOYyMLTctAmXl5XGwBuQ&viewMoreLink=off&sig=5z-u1RMh0wqWaRAzUdiabu0XFufUuEk8leccG_fIAiM=" width="309" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79021318" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- John Wark -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:300px;"><div style="overflow:hidden;position:relative;height:0;padding:148.129676% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/180459550?et=vOpDUN2ES_tPFUxFJ_kuJQ&viewMoreLink=off&sig=yrATz73cbD822XCC270HZ4DC89gAcUV5HkIKOQXo7jk=" width="300" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/180459550" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- David Weir -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:293px;"><div style="overflow:hidden;position:relative;height:0;padding:151.918159% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/105221705?et=xDJUh59nRkRaDL239zxk4Q&viewMoreLink=off&sig=Ep2AFAnSrJ6MH8qPf_cV3RudQebI7ISRdXBlepeHls0=" width="293" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/105221705" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Derek Whyte -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:289px;"><div style="overflow:hidden;position:relative;height:0;padding:153.886010% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78981109?et=XB8-4MpqQvxKSLhMwgODZA&viewMoreLink=off&sig=Dg5i8BOjs68lY0zg7xbUomIozabhNCSSk_CNSqJqpmQ=" width="289" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78981109" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
@else
    <!-- Charlie Adam -->
    <div class="getty localGetty"><img src="/storage/getty/123974487.jpg" /></div>
    <!-- Graham Alexander -->
    <div class="getty localGetty"><img src="/storage/getty/73697613.jpg" /></div>
    <!-- Steve Archibald -->
    <div class="getty localGetty"><img src="/storage/getty/93713688.jpg" /></div>
    <!-- Barry Bannan -->
    <div class="getty localGetty"><img src="/storage/getty/454896684.jpg" /></div>
    <!-- Christophe Berra -->
    <div class="getty localGetty"><img src="/storage/getty/594785086.jpg" /></div>
    <!-- Scott Booth -->
    <div class="getty localGetty"><img src="/storage/getty/1631458.jpg" /></div>
    <!-- Tom Boyd -->
    <div class="getty localGetty"><img src="/storage/getty/52938791.jpg" /></div>
    <!-- Craig Burley -->
    <div class="getty localGetty"><img src="/storage/getty/79036973.jpg" /></div>
    <!-- Colin Calderwood -->
    <div class="getty localGetty"><img src="/storage/getty/79036964.jpg" /></div>
    <!-- John Collins -->
    <div class="getty localGetty"><img src="/storage/getty/1632051.jpg" /></div>
    <!-- Stevie Crawford -->
    <div class="getty localGetty"><img src="/storage/getty/2589887.jpg" /></div>
    <!-- Kenny Dalglish -->
    <div class="getty localGetty"><img src="/storage/getty/93713666.jpg" /></div>
    <!-- Billy Dodds -->
    <div class="getty localGetty"><img src="/storage/getty/1204888.jpg" /></div>
    <!-- Gordon Durie -->
    <div class="getty localGetty"><img src="/storage/getty/1269975.jpg" /></div>
    <!-- Barry Ferguson -->
    <div class="getty localGetty"><img src="/storage/getty/83758471.jpg" /></div>
    <!-- Steven Fletcher -->
    <div class="getty localGetty"><img src="/storage/getty/468026722.jpg" /></div>
    <!-- Kevin Gallacher -->
    <div class="getty localGetty"><img src="/storage/getty/1237354.jpg" /></div>
    <!-- Andy Goram -->
    <div class="getty localGetty"><img src="/storage/getty/1632227.jpg" /></div>
    <!-- Richard Gough -->
    <div class="getty localGetty"><img src="/storage/getty/461528116.jpg" /></div>
    <!-- Frank Gray -->
    <div class="getty localGetty"><img src="/storage/getty/78991342.jpg" /></div>
    <!-- Alan Hansen -->
    <div class="getty localGetty"><img src="/storage/getty/79046585.jpg" /></div>
    <!-- Paul Hartley -->
    <div class="getty localGetty"><img src="/storage/getty/55880488.jpg" /></div>
    <!-- Don Hutchison -->
    <div class="getty localGetty"><img src="/storage/getty/955887.jpg" /></div>
    <!-- Darren Jackson -->
    <div class="getty localGetty"><img src="/storage/getty/1529638.jpg" /></div>
    <!-- Allan Johnston -->
    <div class="getty localGetty"><img src="/storage/getty/1185059.jpg" /></div>
    <!-- Joe Jordan -->
    <div class="getty localGetty"><img src="/storage/getty/78982535.jpg" /></div>
    <!-- Jim Leighton -->
    <div class="getty localGetty"><img src="/storage/getty/174044947.jpg" /></div>
    <!-- Peter Lorimer -->
    <div class="getty localGetty"><img src="/storage/getty/541941058.jpg" /></div>
    <!-- Murdo MacLeod -->
    <div class="getty localGetty"><img src="/storage/getty/79034917.jpg" /></div>
    <!-- Maurice Malpas -->
    <div class="getty localGetty"><img src="/storage/getty/79029134.jpg" /></div>
    <!-- Russell Martin -->
    <div class="getty localGetty"><img src="/storage/getty/179810197.jpg" /></div>
    <!-- Gary McAllister -->
    <div class="getty localGetty"><img src="/storage/getty/1920622.jpg" /></div>
    <!-- Brian McClair -->
    <div class="getty localGetty"><img src="/storage/getty/79648395.jpg" /></div>
    <!-- James McFadden -->
    <div class="getty localGetty"><img src="/storage/getty/71773873.jpg" /></div>
    <!-- Danny McGrain -->
    <div class="getty localGetty"><img src="/storage/getty/79648568.jpg" /></div> 
    <!-- Billy McKinlay -->
    <div class="getty localGetty"><img src="/storage/getty/1639602.jpg" /></div>
    <!-- Tosh McKinlay -->
    <div class="getty localGetty"><img src="/storage/getty/79036874.jpg" /></div>
    <!-- Jackie McNamara -->
    <div class="getty localGetty"><img src="/storage/getty/2522465.jpg" /></div>
    <!-- Kenny Miller -->
    <div class="getty localGetty"><img src="/storage/getty/110933285.jpg" /></div>
    <!-- James Morrison -->
    <div class="getty localGetty"><img src="/storage/getty/487262784.jpg" /></div>
    <!-- David Narey -->
    <div class="getty localGetty"><img src="/storage/getty/79045197.jpg" /></div>
    <!-- Charlie Nicholas -->
    <div class="getty localGetty"><img src="/storage/getty/1640839.jpg" /></div>
    <!-- Steve Nicol -->
    <div class="getty localGetty"><img src="/storage/getty/79647981.jpg" /></div>
    <!-- Davie Provan -->
    <div class="getty localGetty"><img src="/storage/getty/467509150.jpg" /></div>
    <!-- Bruce Rioch -->
    <div class="getty localGetty"><img src="/storage/getty/1232148.jpg" /></div>
    <!-- Matt Richie -->
    <div class="getty localGetty"><img src="/storage/getty/492768774.jpg" /></div>
    <!-- Andrew Robertson -->
    <div class="getty localGetty"><img src="/storage/getty/694752506.jpg" /></div>
    <!-- Barry Robson -->
    <div class="getty localGetty"><img src="/storage/getty/83243743.jpg" /></div>
    <!-- Graeme Sharp -->
    <div class="getty localGetty"><img src="/storage/getty/78968917.jpg" /></div>
    <!-- Graeme Souness -->
    <div class="getty localGetty"><img src="/storage/getty/79652764.jpg" /></div>
    <!-- David Speedie -->
    <div class="getty localGetty"><img src="/storage/getty/89114113.jpg" /></div>
    <!-- Gordon Strachan -->
    <div class="getty localGetty"><img src="/storage/getty/467597720.jpg" /></div>
    <!-- Neil Sullivan -->
    <div class="getty localGetty"><img src="/storage/getty/79021318.jpg" /></div>
    <!-- John Wark -->
    <div class="getty localGetty"><img src="/storage/getty/180459550.jpg" /></div>
    <!-- David Weir -->
    <div class="getty localGetty"><img src="/storage/getty/105221705.jpg" /></div>
    <!-- Derek Whyte -->
    <div class="getty localGetty"><img src="/storage/getty/78981109.jpg" /></div>
@endif