@if (config('app.livemedia'))
    <!-- Roy Aitken -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:390px;"><div style="overflow:hidden;position:relative;height:0;padding:152.307692% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1219756?et=amO2l11uQyZPGuae08WtPw&viewMoreLink=off&sig=85YXgdiTD6ouX9jcLU_p2CvFiZ2yqhA2aoNk17m9ICY=" width="390" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1219756" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Ikechi Anya -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:446px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/454989340" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:133.183857% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/454989340?et=scK7b2XBQr10638V1cWYsg&viewMoreLink=off&sig=Pe7P4NS_kKZjN5IJvnA47TdgZkarJWA3OOF2whkYE7k=&caption=true" width="446" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Jim Baxter -->
	<div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:428px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/1242216" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:138.785047% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1242216?et=A0zKAgGGRpF1ufPMC5hK7g&viewMoreLink=off&sig=G9LsGe9I5DxjTWun0I8HJb7db6_5e6gdkEkbLUv4O1M=&caption=true" width="428" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Jim Bett -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:398px;"><div style="overflow:hidden;position:relative;height:0;padding:149.246231% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78984039?et=9oCACkvuSdJDgeWprQoTow&viewMoreLink=off&sig=9YwzyEWwgQKIdiI3JpchbITjE72o-IuT4lfbAuQHsds=" width="398" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78984039" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Kris Boyd -->
 	<div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:429px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/76590309" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:138.461538% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/76590309?et=_X1hi8i7RkhZbtvG5Z17cA&viewMoreLink=off&sig=HNh9T8hd4onqGfcyIN1E6LEuMkoTjatKZOmzzAcYGBE=&caption=true" width="429" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Alan Brazil -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:406px;"><div style="overflow:hidden;position:relative;height:0;padding:146.305419% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/93713698?et=x4DfIEWnRsB7kTo6oj_HFQ&viewMoreLink=off&sig=qGxmLFzY_wjYw4nrbludCB5drmJYDBQagjUnLOueRew=" width="406" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/93713698" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Billy Bremner -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:387px;"><div style="overflow:hidden;position:relative;height:0;padding:153.488372% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/522789821?et=XIaL7UTgQgh1dbvM8jureQ&viewMoreLink=off&sig=t9ahrjAtHJov3OTgJk-51DeETJeEXG-7LR8BoAQa8Z4=" width="387" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/522789821" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Scott Brown -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:420px;"><div style="overflow:hidden;position:relative;height:0;padding:141.428571% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/97407864?et=MLSh2DLhSct33pVjcVA59A&viewMoreLink=off&sig=RgufglNbfv0QhGR-7xX_lwjx79YkqjZ_F9UUCCDj2aM=" width="420" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/97407864" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Gary Caldwell -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:422px;"><div style="overflow:hidden;position:relative;height:0;padding:140.758294% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/72112310?et=zy1QPRWfQGZmPhyc1jt15A&viewMoreLink=off&sig=v2WYQ2u44M9OO9lX0LD7IimYd2Qu2MJ9AXWkKnzL7bA=" width="422" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/72112310" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Colin Cameron -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:391px;"><div style="overflow:hidden;position:relative;height:0;padding:151.918159% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/945975?et=Us5TwtzYTgtdUXIUStij0A&viewMoreLink=off&sig=j6C60eidrc8hVQkXlcz4UcPCcNVlpblB-utW-yCbKIY=" width="391" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/945975" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Davie Cooper -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:394px;"><div style="overflow:hidden;position:relative;height:0;padding:150.761421% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1633603?et=60Z4BSbOS4dcG2lY1eoDwg&viewMoreLink=off&sig=I_u6igg8uClzFgh2gyRw8HudUvGmqT0kS4E1KiAwT78=" width="394" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1633603" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Christian Dailly -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:361px;"><div style="overflow:hidden;position:relative;height:0;padding:164.542936% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/53158388?et=QN0P6BqNT4hQH0EmKsez-Q&viewMoreLink=off&sig=-vF2bi1qlOGc1EUzv68CJqz2bVNy4xL3zA-ELaRoXag=" width="361" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/53158388" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Callum Davidson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:376px;"><div style="overflow:hidden;position:relative;height:0;padding:157.978723% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1639604?et=Zx53eYbKRutYIUhO8hD2eg&viewMoreLink=off&sig=yNx0FAM6wv0p69E4faUpZXQcU8Od3IBVG6ujj27S04I=" width="376" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1639604" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Willie Donachie -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:403px;"><div style="overflow:hidden;position:relative;height:0;padding:147.394541% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/185838971?et=4eNYVltXQg1b62tXTGINHA&viewMoreLink=off&sig=c-PNpNpxQYQI8rl-HDGRoHFHTCms1WYyygO-3NMzNSU=" width="403" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/185838971" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Iain Durrant -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:422px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/1639603" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:140.758294% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1639603?et=2crCZh6vR5xg6EqbBw5zNw&viewMoreLink=off&sig=gmWDz9l-gGfTOaDchVGDfksxZdTytaawXcz5AvV8OXk=&caption=true" width="422" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Matt Elliott -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:408px;"><div style="overflow:hidden;position:relative;height:0;padding:145.588235% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/944286?et=CwV0iqu6S4p1ULdEGle-lw&viewMoreLink=off&sig=YgOfA9yT0sdHAmU7phasqyp4eHvOyO5Ao0AYtmTH1OA=" width="408" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/944286" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Darren Fletcher -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:325px;"><div style="overflow:hidden;position:relative;height:0;padding:182.769231% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/123974502?et=9oyXH-ZlSbdB12m9G_Bg2w&viewMoreLink=off&sig=oCfQiKrFCxtBDfYAjLwhT3rVnf_7a24F0lxT3Y3nUEA=" width="325" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/123974502" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Archie Gemmill -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:385px;"><div style="overflow:hidden;position:relative;height:0;padding:154.285714% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78981765?et=6RvJ11GVRMlFvIQCer4gjQ&viewMoreLink=off&sig=SDdi33mn6gGqeMSXkL325SPI7zSOYla_0RAoWAxIoPY=" width="385" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78981765" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Scot Gemmill -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:409px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/1994723" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:145.232274% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1994723?et=3lyqgcWIQzpnNloAQs43Sw&viewMoreLink=off&sig=_CzYbSsyaOMauZQzOF4jHqkD-pz5AklWo63QinXVPSo=&caption=true" width="409" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Craig Gordon -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:421px;"><div style="overflow:hidden;position:relative;height:0;padding:141.092637% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/77315138?et=qvVboRfDS-NpV0Cds0R3hw&viewMoreLink=off&sig=RenciraDEUzo0VLWNwlV5-d9-Lpw7fDlhrwNgC8ZLPw=" width="421" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/77315138" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Andy Gray -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:405px;"><div style="overflow:hidden;position:relative;height:0;padding:146.666667% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78987564?et=NM3ujG2xRnFd9c85ZRa4gw&viewMoreLink=off&sig=Suxw4_0IXYowgElDaac73HKFhZIvk_QtZ38BtcMLdlM=" width="405" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78987564" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Grant Hanley -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:393px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/492768978" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:151.145038% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/492768978?et=D7H9Wm3hTVNglN3hFcTeSQ&viewMoreLink=off&sig=Vs4wa87lUwYZOrCjzxAXVPRASICm46hbi_CzBgYqcJM=&caption=true" width="393" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Asa Hartford -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:422px;"><div style="overflow:hidden;position:relative;height:0;padding:140.758294% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/180457736?et=CL51dFPeQWdTtwx9wAu_Kw&viewMoreLink=off&sig=D7VxSOkjDMJJbDOa4xid5e9huGYQ2FkL984JW_7p8Eo=" width="422" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/180457736" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Colin Hendry -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:452px;"><div style="overflow:hidden;position:relative;height:0;padding:131.415929% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79034083?et=vqFZCVV1SUlMO_AMoe9CWQ&viewMoreLink=off&sig=31WGKiaifVpDoifRuFXA3HUsVo9coTu8QSn2nTu4s74=" width="452" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79034083" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Alan Hutton -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/454896754?et=6bBDM8FmTUhykCINd5zsrQ&viewMoreLink=off&sig=QUMI74PlE7HhZVMdeVCzJKBvnNDvpM_G53r9e7cP07E=" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/454896754" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Eoin Jess -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:380px;"><div style="overflow:hidden;position:relative;height:0;padding:156.315789% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78953873?et=nzxVIVnNSrNUnQFDXaWbpg&viewMoreLink=off&sig=W_GMtyd5wmpnbm28SBK1m6p7iIUmp9TTvtIpQBsccFs=" width="380" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78953873" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Mo Johnston -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:392px;"><div style="overflow:hidden;position:relative;height:0;padding:151.530612% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78952740?et=j_QPih-9RThJ-2wOMyh_MQ&viewMoreLink=off&sig=SWPzwWJrFTeCY5rqSNdDXjmBkDjmGbVXohBDEUm8wzs=" width="392" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78952740" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Paul Lambert -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:397px;"><div style="overflow:hidden;position:relative;height:0;padding:149.622166% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1913275?et=YY1gxhR4RhBgHvEf5RcONA&viewMoreLink=off&sig=JfmXPTNstMGULCDVkva4sqP9XDrtHb5OqhmCfJ-1K2Y=" width="397" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1913275" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Denis Law -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:412px;"><div style="overflow:hidden;position:relative;height:0;padding:144.174757% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79051397?et=Bf7RrO-ATmdzjXWhXucr6Q&viewMoreLink=off&sig=mlV5P0Npzb1xAS67fJ2ITsXmMkzChAjEyz_ZRbWS9bM=" width="412" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79051397" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Craig Levein -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:375px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/79648902" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:158.400000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79648902?et=MERzuCbQTsJVuVQvkPDZFQ&viewMoreLink=off&sig=9bmzV_SlGbBX79vvTNNAhoGfBZGSGvAAj6ehS8MOdfM=&caption=true" width="375" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Shaun Maloney -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/179714337?et=24fdj6Z5QoJCkbSgCrHjFQ&viewMoreLink=off&sig=Lcor-GBGdENuUAiR4hGMZf5P8VS1h5D6Mtjd_C3Vnbk=" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/179714337" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- David Marshall -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:395px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/179875064" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:150.379747% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/179875064?et=O9wtcKJPQ1RCWCwOLIrzwA&viewMoreLink=off&sig=Bu_mmFgvV0K6IDrRvkPZWcEvwmvwowtDHKbQlZPxxIw=&caption=true" width="395" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Don Masson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:409px;"><div style="overflow:hidden;position:relative;height:0;padding:145.232274% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79648339?et=BJEwMgecR6F8jiftafPKrw&viewMoreLink=off&sig=4bIIWJ4f_q7HNHsVa_cHdFUyJZRUnLT-vip4eJ4UtDE=" width="409" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79648339" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- James McArthur -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:446px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/455058710" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:133.183857% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/455058710?et=39WWXPx1QgVDPvuSc_cbEQ&viewMoreLink=off&sig=lDtK5dLNGmw0AZ4FB6ghK0nT2NeVHJJrN_PcK8hNIFE=&caption=true" width="446" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Stuart McCall -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1579220?et=AaBgkSZuSqxCS7D6QXV_SQ&viewMoreLink=off&sig=6ymIfmQ-KxP1PRuXNEOr9vzS4ys5fVYN-CGFP4-z2JM=" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1579220" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Neil McCann -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:404px;"><div style="overflow:hidden;position:relative;height:0;padding:147.029703% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1204898?et=pm0vg8h8QVNrI-SKZH8B0w&viewMoreLink=off&sig=0ynlyqmepfVWfWz0SqkaERf_0pkW-m93IQYKRvhgJ9k=" width="404" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1204898" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Ally McCoist -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:390px;"><div style="overflow:hidden;position:relative;height:0;padding:152.307692% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1920119?et=CafBWQ6WRT9MdXnN93pGGA&viewMoreLink=off&sig=VPhh1qekJ5IwW_CdvYhH6q4TB2nxOqlHCffvTLpecY0=" width="390" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1920119" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Allan McGregor -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:428px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/176614238" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:138.785047% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/176614238?et=BcU8P2VXSHx7EvlQGwRuSQ&viewMoreLink=off&sig=173c-9hP37EUXZC7gGCYaDQhf9s872USNaQlPZ9k8og=&caption=true" width="428" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Stuart McKimmie -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1579221?et=NPzyH3ISR4NgRviOS8rW-A&viewMoreLink=off&sig=22v4jzALgAbUEbmoaWqzSakUGxLsOOpBUnGtfhCeCKU=" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1579221" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Alex McLeish -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:404px;"><div style="overflow:hidden;position:relative;height:0;padding:147.029703% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/89113476?et=i5xfoOuySQdHohmodzE_aQ&viewMoreLink=off&sig=dA2_v_1IM2k9NJ0JgAdyaEBnOBL3QepP4zXQ6bRwLYE=" width="404" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/89113476" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Stephen McManus -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:422px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/525859564" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:140.758294% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/525859564?et=eK2EMaY5QYpxAj4e4gtTPw&viewMoreLink=off&sig=pDwFTj9Lb-PnwKGdTvgU68hHJweHCj1XAqF-KU3b6Vw=&caption=true" width="422" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Dave McPherson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:462px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/79648482" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:128.571429% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79648482?et=yN6lnHAaSP9oGKjQe_CkNw&viewMoreLink=off&sig=-9f0qrIg0X2NcHPxOHAEso_X3Prvf6GXEp5lLkaB4DY=&caption=true" width="462" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Paul McStay -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/72388593?et=VurzgAbBTldmmExPiV8C_w&viewMoreLink=off&sig=3rMJvZiGgnEwpbf-C3wOpSz2qDiSsITtxmbNu4OTXUw=" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/72388593" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Willie Miller -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:394px;"><div style="overflow:hidden;position:relative;height:0;padding:150.761421% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1279345?et=rXqEPUNdTGVEsQrVhJZbLg&viewMoreLink=off&sig=1oXgp1J3pUMi91VG4ScnG1tIHxRb_lH2yNXQgJa3Dwk=" width="394" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1279345" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Steven Naismith -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:379px;"><div style="overflow:hidden;position:relative;height:0;padding:156.728232% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/458982678?et=IoRRqu5AQw9uy4IflqJhsA&viewMoreLink=off&sig=k6Z726jFR0RbBYAzZqXxwtPF4_oLralWiq97Qj4pfj0=" width="379" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/458982678" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Gary Naysmith -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:398px;"><div style="overflow:hidden;position:relative;height:0;padding:149.246231% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1913281?et=JL7wB3FaSCxXvtyRkUXtdw&viewMoreLink=off&sig=ZjY5MzcZYtI6CALqZlggaR3RF6L8yEMJ8oUo6RukR5I=" width="398" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1913281" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Pat Nevin -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:385px;"><div style="overflow:hidden;position:relative;height:0;padding:154.285714% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1279783?et=WCmFKNODTx9HmLnHLExRnw&viewMoreLink=off&sig=CZihmU3ne5Bm3hndEwmP-wKf3NPGv9msrxu7vLCEM04=" width="385" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1279783" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Garry O'Connor -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:383px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/71773909" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:155.091384% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/71773909?et=oBtUBT0NQatgHsCywLg7EA&viewMoreLink=off&sig=ylo7Podv7OMVt8bEwZiKrjI5Wca0EHSbAf3xaACsxhU=&caption=true" width="383" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Derek Parlane -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:387px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/78961051" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:153.488372% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78961051?et=dM1hdiJjR5xiQFOpf-7P8g&viewMoreLink=off&sig=PmjiWhRxYxzHQ9tK_0ATtkjqcv25D4eSu9F9Ju8K7rc=&caption=true" width="387" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
    <!-- Steven Pressley -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:400px;"><div style="overflow:hidden;position:relative;height:0;padding:148.500000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/53158392?et=abs9PkRZSU1fOR0YmMpR7w&viewMoreLink=off&sig=O_OB13TocF1pt8VfBAnyxC4SzbL29YsIDS4iCY_dae4=" width="400" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/53158392" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- John Robertson (Forest) -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:395px;"><div style="overflow:hidden;position:relative;height:0;padding:150.379747% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79046400?et=nhWSNfsrSodSVQ1KdApTlg&viewMoreLink=off&sig=Ip2OTcssVlaw2NT4aF5HPiS2elwoJKMQyMAcuyZvFt4=" width="395" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79046400" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Alan Rough -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:405px;"><div style="overflow:hidden;position:relative;height:0;padding:146.666667% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/78961802?et=LyLXsnefQDhvgGy-pUgAHw&viewMoreLink=off&sig=Zfq5VfVgUmlV5EtjmIyN-9yX5wRY1toMYeDXRfuPPTM=" width="405" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/78961802" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Duncan Shearer -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:396px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1579208?et=YRTxjkm8Qa1LD4pNlknm0g&viewMoreLink=off&sig=cf_DaL6oE_OdVd7m8qw4Dp7HDoBaWjQYBHD4P799khQ=" width="396" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1579208" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Robert Snodgrass -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:256px;"><div style="overflow:hidden;position:relative;height:0;padding:173.684211% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/185048583?et=lSFQbBE2TxVmWDGQPC9_8w&viewMoreLink=off&sig=_YUm7LAEAX2yMg0EjnUeIgrTeL8mujrluMZDnVL3vNA=" width="256" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/185048583" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- John Spencer -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:296px;"><div style="overflow:hidden;position:relative;height:0;padding:150.379747% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79053154?et=A0QcZEfFTWRP3uHBaw7vJw&viewMoreLink=off&sig=4D2mx_9wxSivfV1PO7xifDq4UlwBh5Ks4XnQCp4J75w=" width="296" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79053154" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Paul Sturrock -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:303px;"><div style="overflow:hidden;position:relative;height:0;padding:147.029703% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/79652766?et=Hb6mT6pdQtBT3pe9T01ytQ&viewMoreLink=off&sig=AvjAUYpuzHY1ILts3e_ptxucaGz9IwOln0u6oiJsn6o=" width="303" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/79652766" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Steven Thompson -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:274px;"><div style="overflow:hidden;position:relative;height:0;padding:162.295082% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1348652?et=Rm3qY1zsTDNLkqn0XEe_qA&viewMoreLink=off&sig=r-7j6QUbARDUQZB4D1ubi-TuafanMJiEGBEeTe-oWTQ=" width="274" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/1348652" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Andy Webster -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:287px;"><div style="overflow:hidden;position:relative;height:0;padding:155.091384% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/53158401?et=LlUll3ZzTZZECDwZllRwPw&viewMoreLink=off&sig=4W5N9ZvYvS_1kNmVyb1c4js87BOnlxezRBu3P3gczeM=" width="287" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/53158401" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Steven Whittaker -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:297px;"><div style="overflow:hidden;position:relative;height:0;padding:150.000000% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/454874502?et=Qp-wdZ8WSaBM3-YzPQysZw&viewMoreLink=off&sig=s-9qP2c8VENOmzqE7mAXwNEgt7MowQWXl0sFx3HtO70=" width="297" height="445" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div><p style="margin:0;"></p><div style="padding:0;margin:0 0 0 10px;text-align:left;"><a href="http://www.gettyimages.com/detail/454874502" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">View image</a> | <a href="http://www.gettyimages.com" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">gettyimages.com</a></div></div>
    <!-- Lee Wilkie -->
    <div class="getty embed image" style="background-color:#fff;display:inline-block;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#a7a7a7;font-size:11px;width:100%;max-width:399px;"><div style="padding:0;margin:0;text-align:left;"><a href="http://www.gettyimages.com/detail/1994736" target="_blank" style="color:#a7a7a7;text-decoration:none;font-weight:normal !important;border:none;display:inline-block;">Embed from Getty Images</a></div><div style="overflow:hidden;position:relative;height:0;padding:148.872180% 0 0 0;width:100%;"><iframe src="//embed.gettyimages.com/embed/1994736?et=MFxO-SaSS7hWb7IhugwrAg&viewMoreLink=off&sig=o5bP2vrWbJYQgx4r3v2axj6WPYEENm4xU3f_z7XFKeg=&caption=true" width="399" height="594" scrolling="no" frameborder="0" style="display:inline-block;position:absolute;top:0;left:0;width:100%;height:100%;margin:0;"></iframe></div><p style="margin:0;"></p></div>
@else
    <!-- Roy Aitken -->
    <div class="getty localGetty"><img src="/storage/getty/1219756.jpg" /></div>
    <!-- Ikechi Anya -->
    <div class="getty localGetty"><img src="/storage/getty/454989340.jpg" /></div>
    <!-- Jim Baxter -->
	<div class="getty localGetty"><img src="/storage/getty/1242216.jpg" /></div>
    <!-- Jim Bett -->
    <div class="getty localGetty"><img src="/storage/getty/78984039.jpg" /></div>
    <!-- Kris Boyd -->
 	<div class="getty localGetty"><img src="/storage/getty/76590309.jpg" /></div>
    <!-- Alan Brazil -->
    <div class="getty localGetty"><img src="/storage/getty/93713698.jpg" /></div>
    <!-- Billy Bremner -->
    <div class="getty localGetty"><img src="/storage/getty/522789821.jpg" /></div>
    <!-- Scott Brown -->
    <div class="getty localGetty"><img src="/storage/getty/97407864.jpg" /></div>
    <!-- Gary Caldwell -->
    <div class="getty localGetty"><img src="/storage/getty/72112310.jpg" /></div>
    <!-- Colin Cameron -->
    <div class="getty localGetty"><img src="/storage/getty/945975.jpg" /></div>
    <!-- Davie Cooper -->
    <div class="getty localGetty"><img src="/storage/getty/1633603.jpg" /></div>
    <!-- Christian Dailly -->
    <div class="getty localGetty"><img src="/storage/getty/53158388.jpg" /></div>
    <!-- Callum Davidson -->
    <div class="getty localGetty"><img src="/storage/getty/1639604.jpg" /></div>
    <!-- Willie Donachie -->
    <div class="getty localGetty"><img src="/storage/getty/185838971.jpg" /></div>
    <!-- Iain Durrant -->
    <div class="getty localGetty"><img src="/storage/getty/1639603.jpg" /></div>
    <!-- Matt Elliott -->
    <div class="getty localGetty"><img src="/storage/getty/944286.jpg" /></div>
    <!-- Darren Fletcher -->
    <div class="getty localGetty"><img src="/storage/getty/123974502.jpg" /></div>
    <!-- Archie Gemmill -->
    <div class="getty localGetty"><img src="/storage/getty/78981765.jpg" /></div>
    <!-- Scot Gemmill -->
    <div class="getty localGetty"><img src="/storage/getty/1994723.jpg" /></div>
    <!-- Craig Gordon -->
    <div class="getty localGetty"><img src="/storage/getty/77315138.jpg" /></div>
    <!-- Andy Gray -->
    <div class="getty localGetty"><img src="/storage/getty/78987564.jpg" /></div>
    <!-- Grant Hanley -->
    <div class="getty localGetty"><img src="/storage/getty/492768978.jpg" /></div>
    <!-- Asa Hartford -->
    <div class="getty localGetty"><img src="/storage/getty/180457736.jpg" /></div>
    <!-- Colin Hendry -->
    <div class="getty localGetty"><img src="/storage/getty/79034083.jpg" /></div>
    <!-- Alan Hutton -->
    <div class="getty localGetty"><img src="/storage/getty/454896754.jpg" /></div>
    <!-- Eoin Jess -->
    <div class="getty localGetty"><img src="/storage/getty/78953873.jpg" /></div>
    <!-- Mo Johnston -->
    <div class="getty localGetty"><img src="/storage/getty/78952740.jpg" /></div>
    <!-- Paul Lambert -->
    <div class="getty localGetty"><img src="/storage/getty/1913275.jpg" /></div>
    <!-- Denis Law -->
    <div class="getty localGetty"><img src="/storage/getty/79051397.jpg" /></div>
    <!-- Craig Levein -->
    <div class="getty localGetty"><img src="/storage/getty/79648902.jpg" /></div>
    <!-- Shaun Maloney -->
    <div class="getty localGetty"><img src="/storage/getty/179714337.jpg" /></div>
    <!-- David Marshall -->
    <div class="getty localGetty"><img src="/storage/getty/179875064.jpg" /></div>
    <!-- Don Masson -->
    <div class="getty localGetty"><img src="/storage/getty/79648339.jpg" /></div>
    <!-- James McArthur -->
    <div class="getty localGetty"><img src="/storage/getty/455058710.jpg" /></div>
    <!-- Stuart McCall -->
    <div class="getty localGetty"><img src="/storage/getty/1579220.jpg" /></div>
    <!-- Neil McCann -->
    <div class="getty localGetty"><img src="/storage/getty/1204898.jpg" /></div>
    <!-- Ally McCoist -->
    <div class="getty localGetty"><img src="/storage/getty/1920119.jpg" /></div>
    <!-- Allan McGregor -->
    <div class="getty localGetty"><img src="/storage/getty/176614238.jpg" /></div>
    <!-- Stuart McKimmie -->
    <div class="getty localGetty"><img src="/storage/getty/1579221.jpg" /></div>
    <!-- Alex McLeish -->
    <div class="getty localGetty"><img src="/storage/getty/89113476.jpg" /></div>
    <!-- Stephen McManus -->
    <div class="getty localGetty"><img src="/storage/getty/525859564.jpg" /></div>
    <!-- Dave McPherson -->
    <div class="getty localGetty"><img src="/storage/getty/79648482.jpg" /></div>
    <!-- Paul McStay -->
    <div class="getty localGetty"><img src="/storage/getty/72388593.jpg" /></div>
    <!-- Willie Miller -->
    <div class="getty localGetty"><img src="/storage/getty/1279345.jpg" /></div>
    <!-- Steven Naismith -->
    <div class="getty localGetty"><img src="/storage/getty/458982678.jpg" /></div>
    <!-- Gary Naysmith -->
    <div class="getty localGetty"><img src="/storage/getty/1913281.jpg" /></div>
    <!-- Pat Nevin -->
    <div class="getty localGetty"><img src="/storage/getty/1279783.jpg" /></div>
    <!-- Garry O'Connor -->
    <div class="getty localGetty"><img src="/storage/getty/71773909.jpg" /></div>
    <!-- Derek Parlane -->
    <div class="getty localGetty"><img src="/storage/getty/78961051.jpg" /></div>
    <!-- Steven Pressley -->
    <div class="getty localGetty"><img src="/storage/getty/53158392.jpg" /></div>
    <!-- John Robertson (Forest) -->
    <div class="getty localGetty"><img src="/storage/getty/79046400.jpg" /></div>
    <!-- Alan Rough -->
    <div class="getty localGetty"><img src="/storage/getty/78961802.jpg" /></div>
    <!-- Duncan Shearer -->
    <div class="getty localGetty"><img src="/storage/getty/1579208.jpg" /></div>
    <!-- Robert Snodgrass -->
    <div class="getty localGetty"><img src="/storage/getty/185048583.jpg" /></div>
    <!-- John Spencer -->
    <div class="getty localGetty"><img src="/storage/getty/79053154.jpg" /></div>
    <!-- Paul Sturrock -->
    <div class="getty localGetty"><img src="/storage/getty/79652766.jpg" /></div>
    <!-- Steven Thompson -->
    <div class="getty localGetty"><img src="/storage/getty/1348652.jpg" /></div>
    <!-- Andy Webster -->
    <div class="getty localGetty"><img src="/storage/getty/53158401.jpg" /></div>
    <!-- Steven Whittaker -->
    <div class="getty localGetty"><img src="/storage/getty/454874502.jpg" /></div>
    <!-- Lee Wilkie -->
    <div class="getty localGetty"><img src="/storage/getty/1994736.jpg" /></div>
@endif